[package]
name = "integration"
version = "0.0.1"
edition = "2021"

[dependencies]
assert_cmd = "2.0.12"
async-trait = "0.1.77"
byte-unit = { version = "5.1.2", default-features = false, features = [
    "serde",
    "byte",
] }
bytes = "1.4.0"
derive_more = "0.99.17"
futures = "0.3.30"
humantime = "2.1.0"
iggy = "0.1.7"
keyring = "2.3.1"
libc = "0.2.147"
predicates = "3.0.3"
regex = "1.10.2"
serial_test = "3.0.0"
sled = "0.34.7"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.8.8"
uuid = { version = "1.3.3", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.8", features = ["xxh32"] }
