name: qemu_test
on: [push]

jobs:
  qemu_build_and_test:
    name: new build and test
    runs-on: ubuntu-latest
    timeout-minutes: 120
    container:
      image: iggyrs/iggy:latest
      options: --platform linux/arm/v7
      volumes:
        - /home/runner/work/_actions:/home/runner/work/_actions
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "v2"
      - name: Set environment variables
        run: export QEMU_RUNNER=qemu-arm
      - name: Install musl-tools, gnome-keyring and keyutils on Linux
        run: |
          apt-get update --yes && apt-get install --yes musl-tools gnome-keyring keyutils curl libssl-dev pkg-config make perl build-essential
          rm -f $HOME/.local/share/keyrings/*
          echo -n "test" | gnome-keyring-daemon --unlock
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: arm-unknown-linux-musleabi
          toolchain: stable
          args: "--verbose --release"
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: arm-unknown-linux-musleabi
          toolchain: stable
          args: "--verbose --release"
